// <auto-generated />
using System;
using AssistenciaTecnica.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssisTec.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813004800_UpdateCadastroClienteSefaz")]
    partial class UpdateCadastroClienteSefaz
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AssistenciaTecnica.Api.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Documento")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("IndicadorInscricaoEstadual")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("AssistenciaTecnica.Api.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataEntrega")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefeitoRelatado")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEquipamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaModificacaoUtc")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ValorMaoDeObra")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("ValorPecas")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("AssistenciaTecnica.Api.Models.Cliente", b =>
                {
                    b.OwnsOne("AssistenciaTecnica.Api.Models.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoBairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoCep");

                            b1.Property<string>("CodigoMunicipioIbge")
                                .HasMaxLength(7)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoCodigoMunicipioIbge");

                            b1.Property<string>("CodigoPais")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoCodigoPais");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoComplemento");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoLogradouro");

                            b1.Property<string>("Municipio")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoMunicipio");

                            b1.Property<string>("Numero")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoNumero");

                            b1.Property<string>("Pais")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoPais");

                            b1.Property<string>("Uf")
                                .HasMaxLength(2)
                                .HasColumnType("TEXT")
                                .HasColumnName("EnderecoUf");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("AssistenciaTecnica.Api.Models.OrdemServico", b =>
                {
                    b.HasOne("AssistenciaTecnica.Api.Models.Cliente", "Cliente")
                        .WithMany("OrdensServico")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("AssistenciaTecnica.Api.Models.Cliente", b =>
                {
                    b.Navigation("OrdensServico");
                });
#pragma warning restore 612, 618
        }
    }
}
